# check these on https://fabricmc.net/develop if a newer patch exists
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.14.24

# Mod Properties
mod_version=1.0.0
maven_group=fr.smartfolk
archives_base_name=smartfolk-mod

# Dependencies
fabric_version=0.92.2+1.20.1

org.gradle.jvmargs=-Xmx2G
